version: "2.0"
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: vincent@onebrief.com
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - 80:80
volumes:
  pgdata: {}